config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :departments do
    resources :courses do
      resources :sections
    end
    resources :students
  end

  resources :semesters

  resources :student_profiles

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :sections

  scope :sorted, lambda {order("semesters.id ASC")}

  validates :name, :presence => true,
            :length => {:maximum => 50}

end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController


  def index
    @semesters = Semester.sorted
  end

  def show
    #@semester = Semester.find_by(id: params[:id])
  end

  def new
    @semester = Semester.new()
  end

  def create
    @semester = Semester.new(semester_params)
    if @semester.save
      redirect_to(semesters_path)
    else
      render('new')
    end
  end

  private
    def semester_params
      params.require(:semester).permit(:name, :duration_in_month)
    end
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/index.html.erb
<div class=" section index container">
  <div class="row">
<div class=" semester index">
  <h2> Course details </h2>
  <%= link_to("Add New Semester", new_semester_path, class: "btn btn-primary") %>
  <br/><br/>
  <table class="listing" summary="semester-list">
    <tr class="header">
      <th>Id</th>
      <th>Name</th>
      <th>Duration in Month</th>
      <th>Actions</th>
    </tr>
    <% @semesters.each do |semester| %>
      <tr>
        <td>
          <%= semester.id %>
        </td>
        <td>
          <%= semester.name %>
        </td>
        <td>
          <%= semester.duration_in_month %>
        </td>
            <td class="actions">
              <%= link_to("Show", semester_path(semester), class: "btn btn-primary") %>
              <%= link_to("Edit", edit_semester_path(semester), class: "btn btn-primary") %>
              <%= link_to("Destroy", semester_path(semester), class: "btn btn-primary") %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= link_to("Back to Semesters", semesters_path, class: "btn btn-primary") %>
  </div>
</div>

app/views/semesters/new.html.erb
<%= link_to("Back", semeters_path, class: "btn btn-primary") %>

<div class="section create">
  <h2> New Section</h2>

  <%= simple_form_for @semester do |f| %>

    <%= f.input :name %>
    <%= f.input :duration_in_month %>

    <%= f.button :submit %>
  <% end %>
</div>