config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :departments do
    resources :courses do
      resources :sections
    end
    resources :students
  end

  resources :semesters

  resources :student_profiles

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :department
  has_many :student_profiles
  has_many :sections, through: :student_profiles, dependent: :destroy
  #accepts_nested_attributes_for :student_profiles

  scope :sorted, lambda { order("students.id ASC")}

  validates_presence_of :name, :age, :roll
  validates :name, length: {maximum: 50 }
  validates :age, :numericality => { greater_than_or_equal_to: 22, less_than: 40 }
  validates :roll, :numericality => { less_than: 50 }, uniqueness: { scope: :department_id }


  # def information
  #   "#{name} #{age} #{roll}"
  # end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  layout 'application'

  def index
    @department = Department.find(params[:department_id])
    @students = @department.students
  end

  def show
    @department = Department.find(params[:department_id])
    @student = @department.students.find(params[:id])
  end

  def new
    @department = Department.find(params[:department_id])
    @student = Student.new(department_id: params[:department_id])
  end

  def create
    @department = Department.find_by(id: params[:department_id])
    @student = @department.students.create(student_params)
    if @student.save
      flash[:notice] = "The student has been created successfully!"
      redirect_to(department_students_path)
    else
      render('new')
    end
  end

  def edit
    @department = Department.find_by(id: params[:department_id])
    @student = @department.students.find_by(id: params[:id])
  end

  def update
    @student = Student.find_by(id: params[:id])
    @student.update_attributes(student_params)
    if @student.save
      redirect_to(department_student_path)
    else
      render('edit')
    end
  end

  def destroy
    @department = Department.find(params[:department_id])
    @student = @department.students.find(params[:id])
    @student.destroy
      redirect_to(department_students_path, notice: 'Delete Success!')
  end

  private
  def student_params
    params.require(:student).permit(:name, :age, :roll,
      student_profile_ids: [], student_profiles_attributes:[:year, :result])
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<table class="table table-bordered table-stripped width_setting">
  <tr>
    <th> Department Id </th>
    <td> <%= f.text_field(:department_id) %> </td>
  </tr>
  <tr>
    <th>Semester Id </th>
    <td> <%= f.text_field(:semester_id) %> </td>
  </tr>
  <tr>
    <th>Name</th>
    <td> <%= f.text_field(:name) %> </td>
  </tr>
  <tr>
    <th>Age</th>
    <td> <%= f.text_field(:age) %> </td>
  </tr>
  <tr>
    <th>Roll</th>
    <td> <%= f.text_field(:roll) %> </td>
  </tr>
</table>

app/views/students/edit.html.erb
<div class=" section index container">
  <div class="row">
    <%= link_to("Back", department_students_path, class: "back-list" ) %>


    <%= simple_form_for ([@department, @student]) do |f| %>

      <%= f.input :name %>
      <%= f.input :age %>
      <%= f.input :roll %>

      <%= f.fields_for :student_profile do |ff| %>
        <%= ff.input :year %>
        <%= ff.input :result %>

      <% end %>

      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<div class=" student index container">
  <div class="row">
    <%= link_to("Back", department_path(@department), class: "back-link") %>
    <div class=" student index">
      <h2> Students List </h2>
      <%= link_to("Add New Student", new_department_student_path, class: "add-new") %>
      <br/><br/>
      <table class="table table-bordered table-stripped width_setting" class="listing" summary="section-list">
        <tr class="header">
          <th>Id</th>
          <th> Name</th>
          <th> Age</th>
          <th> Roll</th>
          <th> Actions</th>
        </tr>
        <% @students.each do |student| %>
          <tr>
            <td>
              <%= student.id %>
            </td>
            <td>
              <%= student.name %>
            </td>
            <td>
              <%= student.age %>
            </td>
            <td>
              <%= student.roll %>
            </td>
            <td class="actions">
              <%= link_to("Show", department_student_path(@department, student), class: "btn btn-primary") %>
              <%= link_to("Edit", edit_department_student_path(@department, student), class: "btn btn-primary") %>
              <%= link_to("Destroy", department_student_path(@department, student), method: :delete, data: {confirm: "Are you sure want to delete this?"}, class: "btn btn-primary") %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class=" section index container">
  <div class="row">
    <%= link_to("Back", department_students_path, class: "back-list" ) %>

    <%= simple_form_for [@department, @student] do |f| %>
        <%= f.input :name %>
        <%= f.input :age, collection: 22..40, prompt: "Select age", selected: 18 %>
        <%= f.input :roll, collection: 1..50, prompt: "Select roll", selected: 50 %>

        <%= f.button :submit %>
    <% end %>

    <%= link_to 'Back', department_students_path %>
  </div>
</div>

app/views/students/show.html.erb
<div class=" section index container">
  <div class="row">

<%= link_to("Back", department_students_path, class: "btn btn-primary" ) %>

<div class="Student show">
  <h2> Show Student</h2>
  <table class="table table-bordered table-stripped width_setting">
    <tr class="border">
      <th>Name </th>
      <td> <%= @student.name %></td>
    </tr>
    <tr>
      <th>Age </th>
      <td> <%= @student.age %></td>
    </tr>
    <tr>
      <th>Roll </th>
      <td> <%= @student.roll %></td>
    </tr>
  </table>
</div>

<br/><br/><br/><br/>

<div class="student details">
  <h2> Courses Taken This Semester</h2>
  <table class="table table-bordered table-stripped width_setting">
    <tr>
      <th>Course Code</th>
      <th>Course Name</th>
      <th>Section No</th>
      <th>Department</th>
    </tr>
    <% @student.sections.each do |section| %>
     <tr>
       <td>
         <%= section.course.course_code %>
       </td>
       <td>
         <%= section.course.name %>
       </td>
       <td>
         <%= section.section_no %>
       </td>
       <td>
         <%= section.course.department.name %>
       </td>
      </tr>
    <% end  %>
  </table>
</div>
  </div>
</div>