config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :departments do
    resources :courses do
      resources :sections
    end
    resources :students
  end

  resources :semesters

  resources :student_profiles

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :students, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :courses, dependent: :destroy

  scope :sorted, lambda { order("departments.id ASC")}

  validates :name, :presence => true,
            :length => {:maximum => 50}, uniqueness: true


end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController


  def index
    @departments = Department.sorted
  end

  def show
    @department = Department.find(params[:id])
    @course = @department.courses
    @student = @department.students
  end

  def new
    @department = Department.new()
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:notice] = "{name} has been created successfully!"
      redirect_to(departments_path)
    else
      flash[:errors] = @department.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])
    @department.update_attributes(department_params)
    if @department.save
      flash[:notice] = "The Department has been updated successfully!"
      redirect_to(departments_path)
    else
      flash[:errors] = @department.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy
    redirect_to(departments_path, notice: 'Delete Success!')
  end

  private
    def department_params
      params.require(:department).permit(:name, :credit)
    end

end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/views/departments/_form.html.erb
<div class=" section index container">
  <div class="row">
    <table class="table table-bordered table-stripped width_setting">
      <tr>
        <th>Name: </th>
        <td> <%= f.text_field(:name) %> </td>
      </tr>
      <tr>
        <th>Credit: </th>
        <td> <%= f.text_field(:credit) %> </td>
      </tr>
    </table>
  </div>
</div>

app/views/departments/edit.html.erb
<%= link_to("Back", departments_path, class: "back-list" ) %>

<div class="department update">
  <h2> Update Department</h2>

  <%= simple_form_for @department do |f| %>

  <%= render(partial: 'form', locals: {f: f}) %>


  <%= f.button :submit %>

  <% end %>
</div>

app/views/departments/index.html.erb
<div class=" section index container">
  <div class="row">
    <div class="department index">
      <h2> Index Department </h2>
      <%= link_to("Add New Department", new_department_path ) %>
      <table class="table table-bordered table-stripped width_setting" class="listing" summary="subject-list">
        <tr class="header">
          <th> Department Id</th>
          <th> Departments</th>
          <th> Credit</th>
          <th> Students</th>
          <th> Courses</th>
          <th> Actions</th>
        </tr>
        <% @departments.each do |department| %>
        <tr>
          <td>
            <%= department.id %>
          </td>
          <td>
            <%= department.name %>
          </td>
          <td>
            <%= department.credit %>
          </td>
          <td>
            <%= department.students.count %>
          </td>
          <td>
            <%= department.courses.count %>
          </td>
          <td class="actions">
            <%= link_to("Show", department_path(department) , class: "link-show", class: "btn btn-primary") %>
            <%= link_to("Edit", edit_department_path(department), class: "link-edit", class: "btn btn-primary") %>
            <%= link_to("Destroy", department_path(department), method: :delete, data: {confirm: "Are you sure want to delete this?"}, class: "btn btn-primary") %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class=" section index container">
  <div class="row">
    <%= link_to("Back", departments_path, class: "back-list" ) %>

    <div class="department new">
      <h2> New Department</h2>

      <%= simple_form_for @department do |f| %>

      <%= render(partial: 'form', locals: {f: f}) %>

          <%= f.button :submit %>

      <% end %>
    </div>
  </div>
</div>

app/views/departments/show.html.erb
<div class=" section index container">
  <div class="row">
    <%= link_to("Back", departments_path, class: "back-list" ) %>

    <div class="department show">
      <h2> Show Department</h2>
      <table class="table table-bordered table-stripped width_setting" class="department Detail View">
        <tr>
          <th>Name </th>
          <td> <%= @department.name %></td>
        </tr>
        <tr>
          <th>Created At </th>
          <td> <%= @department.created_at %></td>
        </tr>
        <tr>
          <th>Updated At </th>
          <td> <%= @department.updated_at %></td>
        </tr>
      </table>
    </div>
    <%= link_to("Courses", department_courses_path(@department)) %>
    <%= link_to("Students", department_students_path(@department)) %>
  </div>
</div>