config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  resources :departments do
    resources :courses do
      resources :sections
    end
    resources :students
  end

  resources :semesters

  resources :student_profiles

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :semester
  belongs_to :teacher
  belongs_to :course
  has_many :student_profiles
  has_many :students, through: :student_profiles, dependent: :destroy

  scope :sorted, lambda {order("sections.section_no ASC")}

  validates_presence_of :section_no
  validates_uniqueness_of :section_no, scope: [:course_id]
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  layout  'application'

  def index
    @department = Department.find_by(id: params[:department_id])
    @course = @department.courses.find_by(id: params[:course_id])
    @section = Section.where(id: params[:ids])
    @sections = @course.sections.sorted
  end

  def show
    @department = Department.find_by(id: params[:department_id])
    @course = @department.courses.find_by(id: params[:course_id])
    @section = @course.sections.find_by(id: params[:id])
  end

  def new
    @department = Department.find_by(id: params[:department_id])
    @course = @department.courses.find_by(id: params[:course_id])
    @section = Section.new(course_id: params[:course_id])
  end

  def create
    @department = Department.find(params[:department_id])
    @course = @department.courses.find(params[:course_id])
    @section = @course.sections.create(section_params)
    
    if @section.save
      flash[:notice] = "The section has been created successfully!"
      redirect_to(department_course_sections_path)
    else
      render('new')
    end
  end

  private
    def section_params
      params.require(:section).permit(:section_no)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
  def sections_list
    a = Section.all.map {|sec| [sec.id, sec.section_no]}
    Hash[a]
  end
end

app/views/sections/_form.html.erb
<table>
  <tr>
    <th>Section No</th>
    <td> <%= f.text_field(:section_no) %> </td>
  </tr>
</table>

app/views/sections/index.html.erb
<div class=" section index container">
  <div class="row">
    <h4><span style="font-weight: bold;">Department:</span> <%= @course.department.name %> </h4>
  <h4>Course: <%= @course.name %> </h4>
  <h2> Section details </h2>

  <%= link_to("Add New Section", new_department_course_section_path, class: 'btn btn-primary') %>
  <br/><br/>
  <table class="table table-bordered table-stripped width_setting" class="listing" summary="section-list">
    <tr class="header">
      <th>Id</th>
      <th> Section_no</th>
      <th> Student Profile</th>
      <th> Actions</th>
    </tr>
    <% @sections.each do |section| %>
      <tr>
        <td>
          <%= section.id %>
        </td>
        <td>
          <%= section.section_no %>
        </td>
        <td class="actions">
          <%= link_to(section.student_profiles.uniq.count, student_profiles_path(ids: section.student_profiles.ids, section_id: section.id))%>
        </td>
        <td class="actions">
          <%= link_to("Show", department_course_section_path(@department, @course, section), class: 'btn btn-primary') %>
          <%= link_to("Edit", edit_department_course_section_path(@department, @course, section), class: 'btn btn-primary') %>
          <%= link_to("Destroy", department_course_section_path(@department, @course, section), class: 'btn btn-primary') %>
        </td>
      </tr>
    <% end %>
  </table>
    <%= link_to("Back", department_courses_path, class: 'btn btn-primary') %>
  </div>
</div>

app/views/sections/new.html.erb
<%= link_to("Back", department_course_sections_path, class: "back-list" ) %>

<div class="section create">
  <h2> New Section</h2>

  <%= simple_form_for [@department, @course, @section] do |f| %>

    <%= f.input :section_no %>

    <%= f.button :submit %>
  <% end %>
</div>

app/views/sections/show.html.erb
<div class=" section index container">
  <div class="row">
    <%= link_to("Back", department_course_sections_path, class: "back-list" ) %>
    <div class="section show">
      <h2> Show Section</h2>
      <table class="table table-bordered table-stripped width_setting">
        <tr>
          <th>Section No: </th>
          <td> <%= @section.section_no %></td>
        </tr>
        <tr>
          <th>department: </th>
          <td> <%= @section.course.department.name %></td>
        </tr>
      </table>
    </div>
  </div>
</div>